eureka:
  clint:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9091
spring:
  application:
    name: E-learning-website
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true